spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hsp
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/template
    suffix: .html